// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server_only/cmd_security.server.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.Cmd.Security
{

    /// <summary>Holder for reflection information generated from server_only/cmd_security.server.proto</summary>
    public static partial class CmdSecurityServerReflection
    {

        #region Descriptor
        /// <summary>File descriptor for server_only/cmd_security.server.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static CmdSecurityServerReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "CiVzZXJ2ZXJfb25seS9jbWRfc2VjdXJpdHkuc2VydmVyLnByb3RvEg5wcm90",
                  "b19zZWN1cml0eSKAAQoWR2FtZUxvZ2luTm90aWZ5UmVxdWVzdBILCgN1aWQY",
                  "ASABKA0SFAoMYWNjb3VudF90eXBlGAIgASgNEg8KB2FjY291bnQYAyABKAkS",
                  "EAoIcGxhdGZvcm0YBCABKA0SDgoGcmVnaW9uGAUgASgJEhAKCGJpel9nYW1l",
                  "GAYgASgJIoEBChdHYW1lTG9nb3V0Tm90aWZ5UmVxdWVzdBILCgN1aWQYASAB",
                  "KA0SFAoMYWNjb3VudF90eXBlGAIgASgNEg8KB2FjY291bnQYAyABKAkSEAoI",
                  "cGxhdGZvcm0YBCABKA0SDgoGcmVnaW9uGAUgASgJEhAKCGJpel9nYW1lGAYg",
                  "ASgJIiAKEUdhbWVIZWFydEJlYXRJbmZvEgsKA3VpZBgBIAMoDSL1AQoaR2Ft",
                  "ZUhlYXJ0QmVhdE5vdGlmeVJlcXVlc3QSWgoRcGxhdGZvcm1fdWlkX2xpc3QY",
                  "ASADKAsyPy5wcm90b19zZWN1cml0eS5HYW1lSGVhcnRCZWF0Tm90aWZ5UmVx",
                  "dWVzdC5QbGF0Zm9ybVVpZExpc3RFbnRyeRIOCgZyZWdpb24YAiABKAkSEAoI",
                  "Yml6X2dhbWUYAyABKAkaWQoUUGxhdGZvcm1VaWRMaXN0RW50cnkSCwoDa2V5",
                  "GAEgASgNEjAKBXZhbHVlGAIgASgLMiEucHJvdG9fc2VjdXJpdHkuR2FtZUhl",
                  "YXJ0QmVhdEluZm86AjgBKpIBCghQbGF0Zm9ybRIKCgZVbmtvd24QABIHCgNJ",
                  "T1MQARILCgdBbmRyb2lkEAISBgoCUEMQAxIHCgNXRUIQBBIHCgNXQVAQBRIG",
                  "CgJQUxAGEgwKCE5pbnRlbmRvEAcSEAoMQ2xvdWRBbmRyb2lkEAgSCwoHQ2xv",
                  "dWRQQxAJEgwKCENsb3VkSU9TEAoSBwoDUFM1EAtCFaoCElByb3RvLkNtZC5T",
                  "ZWN1cml0eWIGcHJvdG8z"));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(new[] { typeof(global::Proto.Cmd.Security.Platform), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Cmd.Security.GameLoginNotifyRequest), global::Proto.Cmd.Security.GameLoginNotifyRequest.Parser, new[]{ "Uid", "AccountType", "Account", "Platform", "Region", "BizGame" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Cmd.Security.GameLogoutNotifyRequest), global::Proto.Cmd.Security.GameLogoutNotifyRequest.Parser, new[]{ "Uid", "AccountType", "Account", "Platform", "Region", "BizGame" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Cmd.Security.GameHeartBeatInfo), global::Proto.Cmd.Security.GameHeartBeatInfo.Parser, new[]{ "Uid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Cmd.Security.GameHeartBeatNotifyRequest), global::Proto.Cmd.Security.GameHeartBeatNotifyRequest.Parser, new[]{ "PlatformUidList", "Region", "BizGame" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
                }));
        }
        #endregion

    }
    #region Enums
    public enum Platform
    {
        [pbr::OriginalName("Unkown")] Unkown = 0,
        [pbr::OriginalName("IOS")] Ios = 1,
        [pbr::OriginalName("Android")] Android = 2,
        [pbr::OriginalName("PC")] Pc = 3,
        [pbr::OriginalName("WEB")] Web = 4,
        [pbr::OriginalName("WAP")] Wap = 5,
        [pbr::OriginalName("PS")] Ps = 6,
        [pbr::OriginalName("Nintendo")] Nintendo = 7,
        [pbr::OriginalName("CloudAndroid")] CloudAndroid = 8,
        [pbr::OriginalName("CloudPC")] CloudPc = 9,
        [pbr::OriginalName("CloudIOS")] CloudIos = 10,
        [pbr::OriginalName("PS5")] Ps5 = 11,
    }

    #endregion

    #region Messages
    public sealed partial class GameLoginNotifyRequest : pb::IMessage<GameLoginNotifyRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<GameLoginNotifyRequest> _parser = new pb::MessageParser<GameLoginNotifyRequest>(() => new GameLoginNotifyRequest());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<GameLoginNotifyRequest> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Proto.Cmd.Security.CmdSecurityServerReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameLoginNotifyRequest()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameLoginNotifyRequest(GameLoginNotifyRequest other) : this()
        {
            uid_ = other.uid_;
            accountType_ = other.accountType_;
            account_ = other.account_;
            platform_ = other.platform_;
            region_ = other.region_;
            bizGame_ = other.bizGame_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameLoginNotifyRequest Clone()
        {
            return new GameLoginNotifyRequest(this);
        }

        /// <summary>Field number for the "uid" field.</summary>
        public const int UidFieldNumber = 1;
        private uint uid_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Uid
        {
            get { return uid_; }
            set
            {
                uid_ = value;
            }
        }

        /// <summary>Field number for the "account_type" field.</summary>
        public const int AccountTypeFieldNumber = 2;
        private uint accountType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint AccountType
        {
            get { return accountType_; }
            set
            {
                accountType_ = value;
            }
        }

        /// <summary>Field number for the "account" field.</summary>
        public const int AccountFieldNumber = 3;
        private string account_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Account
        {
            get { return account_; }
            set
            {
                account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "platform" field.</summary>
        public const int PlatformFieldNumber = 4;
        private uint platform_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Platform
        {
            get { return platform_; }
            set
            {
                platform_ = value;
            }
        }

        /// <summary>Field number for the "region" field.</summary>
        public const int RegionFieldNumber = 5;
        private string region_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Region
        {
            get { return region_; }
            set
            {
                region_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "biz_game" field.</summary>
        public const int BizGameFieldNumber = 6;
        private string bizGame_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string BizGame
        {
            get { return bizGame_; }
            set
            {
                bizGame_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as GameLoginNotifyRequest);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(GameLoginNotifyRequest other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Uid != other.Uid) return false;
            if (AccountType != other.AccountType) return false;
            if (Account != other.Account) return false;
            if (Platform != other.Platform) return false;
            if (Region != other.Region) return false;
            if (BizGame != other.BizGame) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Uid != 0) hash ^= Uid.GetHashCode();
            if (AccountType != 0) hash ^= AccountType.GetHashCode();
            if (Account.Length != 0) hash ^= Account.GetHashCode();
            if (Platform != 0) hash ^= Platform.GetHashCode();
            if (Region.Length != 0) hash ^= Region.GetHashCode();
            if (BizGame.Length != 0) hash ^= BizGame.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Uid != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Uid);
      }
      if (AccountType != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(AccountType);
      }
      if (Account.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Account);
      }
      if (Platform != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Platform);
      }
      if (Region.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Region);
      }
      if (BizGame.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(BizGame);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Uid != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(Uid);
            }
            if (AccountType != 0)
            {
                output.WriteRawTag(16);
                output.WriteUInt32(AccountType);
            }
            if (Account.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(Account);
            }
            if (Platform != 0)
            {
                output.WriteRawTag(32);
                output.WriteUInt32(Platform);
            }
            if (Region.Length != 0)
            {
                output.WriteRawTag(42);
                output.WriteString(Region);
            }
            if (BizGame.Length != 0)
            {
                output.WriteRawTag(50);
                output.WriteString(BizGame);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Uid != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uid);
            }
            if (AccountType != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AccountType);
            }
            if (Account.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
            }
            if (Platform != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Platform);
            }
            if (Region.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Region);
            }
            if (BizGame.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(BizGame);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(GameLoginNotifyRequest other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Uid != 0)
            {
                Uid = other.Uid;
            }
            if (other.AccountType != 0)
            {
                AccountType = other.AccountType;
            }
            if (other.Account.Length != 0)
            {
                Account = other.Account;
            }
            if (other.Platform != 0)
            {
                Platform = other.Platform;
            }
            if (other.Region.Length != 0)
            {
                Region = other.Region;
            }
            if (other.BizGame.Length != 0)
            {
                BizGame = other.BizGame;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uid = input.ReadUInt32();
            break;
          }
          case 16: {
            AccountType = input.ReadUInt32();
            break;
          }
          case 26: {
            Account = input.ReadString();
            break;
          }
          case 32: {
            Platform = input.ReadUInt32();
            break;
          }
          case 42: {
            Region = input.ReadString();
            break;
          }
          case 50: {
            BizGame = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Uid = input.ReadUInt32();
                            break;
                        }
                    case 16:
                        {
                            AccountType = input.ReadUInt32();
                            break;
                        }
                    case 26:
                        {
                            Account = input.ReadString();
                            break;
                        }
                    case 32:
                        {
                            Platform = input.ReadUInt32();
                            break;
                        }
                    case 42:
                        {
                            Region = input.ReadString();
                            break;
                        }
                    case 50:
                        {
                            BizGame = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class GameLogoutNotifyRequest : pb::IMessage<GameLogoutNotifyRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<GameLogoutNotifyRequest> _parser = new pb::MessageParser<GameLogoutNotifyRequest>(() => new GameLogoutNotifyRequest());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<GameLogoutNotifyRequest> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Proto.Cmd.Security.CmdSecurityServerReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameLogoutNotifyRequest()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameLogoutNotifyRequest(GameLogoutNotifyRequest other) : this()
        {
            uid_ = other.uid_;
            accountType_ = other.accountType_;
            account_ = other.account_;
            platform_ = other.platform_;
            region_ = other.region_;
            bizGame_ = other.bizGame_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameLogoutNotifyRequest Clone()
        {
            return new GameLogoutNotifyRequest(this);
        }

        /// <summary>Field number for the "uid" field.</summary>
        public const int UidFieldNumber = 1;
        private uint uid_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Uid
        {
            get { return uid_; }
            set
            {
                uid_ = value;
            }
        }

        /// <summary>Field number for the "account_type" field.</summary>
        public const int AccountTypeFieldNumber = 2;
        private uint accountType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint AccountType
        {
            get { return accountType_; }
            set
            {
                accountType_ = value;
            }
        }

        /// <summary>Field number for the "account" field.</summary>
        public const int AccountFieldNumber = 3;
        private string account_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Account
        {
            get { return account_; }
            set
            {
                account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "platform" field.</summary>
        public const int PlatformFieldNumber = 4;
        private uint platform_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Platform
        {
            get { return platform_; }
            set
            {
                platform_ = value;
            }
        }

        /// <summary>Field number for the "region" field.</summary>
        public const int RegionFieldNumber = 5;
        private string region_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Region
        {
            get { return region_; }
            set
            {
                region_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "biz_game" field.</summary>
        public const int BizGameFieldNumber = 6;
        private string bizGame_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string BizGame
        {
            get { return bizGame_; }
            set
            {
                bizGame_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as GameLogoutNotifyRequest);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(GameLogoutNotifyRequest other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Uid != other.Uid) return false;
            if (AccountType != other.AccountType) return false;
            if (Account != other.Account) return false;
            if (Platform != other.Platform) return false;
            if (Region != other.Region) return false;
            if (BizGame != other.BizGame) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Uid != 0) hash ^= Uid.GetHashCode();
            if (AccountType != 0) hash ^= AccountType.GetHashCode();
            if (Account.Length != 0) hash ^= Account.GetHashCode();
            if (Platform != 0) hash ^= Platform.GetHashCode();
            if (Region.Length != 0) hash ^= Region.GetHashCode();
            if (BizGame.Length != 0) hash ^= BizGame.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Uid != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Uid);
      }
      if (AccountType != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(AccountType);
      }
      if (Account.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Account);
      }
      if (Platform != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Platform);
      }
      if (Region.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Region);
      }
      if (BizGame.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(BizGame);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Uid != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(Uid);
            }
            if (AccountType != 0)
            {
                output.WriteRawTag(16);
                output.WriteUInt32(AccountType);
            }
            if (Account.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(Account);
            }
            if (Platform != 0)
            {
                output.WriteRawTag(32);
                output.WriteUInt32(Platform);
            }
            if (Region.Length != 0)
            {
                output.WriteRawTag(42);
                output.WriteString(Region);
            }
            if (BizGame.Length != 0)
            {
                output.WriteRawTag(50);
                output.WriteString(BizGame);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Uid != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uid);
            }
            if (AccountType != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AccountType);
            }
            if (Account.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
            }
            if (Platform != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Platform);
            }
            if (Region.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Region);
            }
            if (BizGame.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(BizGame);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(GameLogoutNotifyRequest other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Uid != 0)
            {
                Uid = other.Uid;
            }
            if (other.AccountType != 0)
            {
                AccountType = other.AccountType;
            }
            if (other.Account.Length != 0)
            {
                Account = other.Account;
            }
            if (other.Platform != 0)
            {
                Platform = other.Platform;
            }
            if (other.Region.Length != 0)
            {
                Region = other.Region;
            }
            if (other.BizGame.Length != 0)
            {
                BizGame = other.BizGame;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uid = input.ReadUInt32();
            break;
          }
          case 16: {
            AccountType = input.ReadUInt32();
            break;
          }
          case 26: {
            Account = input.ReadString();
            break;
          }
          case 32: {
            Platform = input.ReadUInt32();
            break;
          }
          case 42: {
            Region = input.ReadString();
            break;
          }
          case 50: {
            BizGame = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Uid = input.ReadUInt32();
                            break;
                        }
                    case 16:
                        {
                            AccountType = input.ReadUInt32();
                            break;
                        }
                    case 26:
                        {
                            Account = input.ReadString();
                            break;
                        }
                    case 32:
                        {
                            Platform = input.ReadUInt32();
                            break;
                        }
                    case 42:
                        {
                            Region = input.ReadString();
                            break;
                        }
                    case 50:
                        {
                            BizGame = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class GameHeartBeatInfo : pb::IMessage<GameHeartBeatInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<GameHeartBeatInfo> _parser = new pb::MessageParser<GameHeartBeatInfo>(() => new GameHeartBeatInfo());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<GameHeartBeatInfo> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Proto.Cmd.Security.CmdSecurityServerReflection.Descriptor.MessageTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameHeartBeatInfo()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameHeartBeatInfo(GameHeartBeatInfo other) : this()
        {
            uid_ = other.uid_.Clone();
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameHeartBeatInfo Clone()
        {
            return new GameHeartBeatInfo(this);
        }

        /// <summary>Field number for the "uid" field.</summary>
        public const int UidFieldNumber = 1;
        private static readonly pb::FieldCodec<uint> _repeated_uid_codec
            = pb::FieldCodec.ForUInt32(10);
        private readonly pbc::RepeatedField<uint> uid_ = new pbc::RepeatedField<uint>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<uint> Uid
        {
            get { return uid_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as GameHeartBeatInfo);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(GameHeartBeatInfo other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!uid_.Equals(other.uid_)) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            hash ^= uid_.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      uid_.WriteTo(output, _repeated_uid_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            uid_.WriteTo(ref output, _repeated_uid_codec);
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            size += uid_.CalculateSize(_repeated_uid_codec);
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(GameHeartBeatInfo other)
        {
            if (other == null)
            {
                return;
            }
            uid_.Add(other.uid_);
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            uid_.AddEntriesFrom(input, _repeated_uid_codec);
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                    case 8:
                        {
                            uid_.AddEntriesFrom(ref input, _repeated_uid_codec);
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class GameHeartBeatNotifyRequest : pb::IMessage<GameHeartBeatNotifyRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<GameHeartBeatNotifyRequest> _parser = new pb::MessageParser<GameHeartBeatNotifyRequest>(() => new GameHeartBeatNotifyRequest());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<GameHeartBeatNotifyRequest> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Proto.Cmd.Security.CmdSecurityServerReflection.Descriptor.MessageTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameHeartBeatNotifyRequest()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameHeartBeatNotifyRequest(GameHeartBeatNotifyRequest other) : this()
        {
            platformUidList_ = other.platformUidList_.Clone();
            region_ = other.region_;
            bizGame_ = other.bizGame_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GameHeartBeatNotifyRequest Clone()
        {
            return new GameHeartBeatNotifyRequest(this);
        }

        /// <summary>Field number for the "platform_uid_list" field.</summary>
        public const int PlatformUidListFieldNumber = 1;
        private static readonly pbc::MapField<uint, global::Proto.Cmd.Security.GameHeartBeatInfo>.Codec _map_platformUidList_codec
            = new pbc::MapField<uint, global::Proto.Cmd.Security.GameHeartBeatInfo>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Proto.Cmd.Security.GameHeartBeatInfo.Parser), 10);
        private readonly pbc::MapField<uint, global::Proto.Cmd.Security.GameHeartBeatInfo> platformUidList_ = new pbc::MapField<uint, global::Proto.Cmd.Security.GameHeartBeatInfo>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::MapField<uint, global::Proto.Cmd.Security.GameHeartBeatInfo> PlatformUidList
        {
            get { return platformUidList_; }
        }

        /// <summary>Field number for the "region" field.</summary>
        public const int RegionFieldNumber = 2;
        private string region_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Region
        {
            get { return region_; }
            set
            {
                region_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "biz_game" field.</summary>
        public const int BizGameFieldNumber = 3;
        private string bizGame_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string BizGame
        {
            get { return bizGame_; }
            set
            {
                bizGame_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as GameHeartBeatNotifyRequest);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(GameHeartBeatNotifyRequest other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!PlatformUidList.Equals(other.PlatformUidList)) return false;
            if (Region != other.Region) return false;
            if (BizGame != other.BizGame) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            hash ^= PlatformUidList.GetHashCode();
            if (Region.Length != 0) hash ^= Region.GetHashCode();
            if (BizGame.Length != 0) hash ^= BizGame.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      platformUidList_.WriteTo(output, _map_platformUidList_codec);
      if (Region.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Region);
      }
      if (BizGame.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BizGame);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            platformUidList_.WriteTo(ref output, _map_platformUidList_codec);
            if (Region.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(Region);
            }
            if (BizGame.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(BizGame);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            size += platformUidList_.CalculateSize(_map_platformUidList_codec);
            if (Region.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Region);
            }
            if (BizGame.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(BizGame);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(GameHeartBeatNotifyRequest other)
        {
            if (other == null)
            {
                return;
            }
            platformUidList_.MergeFrom(other.platformUidList_);
            if (other.Region.Length != 0)
            {
                Region = other.Region;
            }
            if (other.BizGame.Length != 0)
            {
                BizGame = other.BizGame;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            platformUidList_.AddEntriesFrom(input, _map_platformUidList_codec);
            break;
          }
          case 18: {
            Region = input.ReadString();
            break;
          }
          case 26: {
            BizGame = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            platformUidList_.AddEntriesFrom(ref input, _map_platformUidList_codec);
                            break;
                        }
                    case 18:
                        {
                            Region = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            BizGame = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    #endregion

}

#endregion Designer generated code